/**
 * Настроения мозаики (v3 hub): четыре curated-канала хаба.
 *
 * Единая точка правды для: фильтров мозаики (/feed), SEO-страниц
 * /moods/[mood], OG-карточек и стикеров на карточках. Добавление
 * нового настроения = одна запись здесь + строка в i18n.
 */

export type MoodKey = "swag" | "creepy" | "future" | "ufo";

export interface MoodDef {
  key: MoodKey;
  /** кислотный акцент настроения (стикеры, бордеры, OG) */
  color: string;
  /** глиф в духе zine — без emoji, только типографика */
  glyph: string;
  /** EN-факты для SEO-страниц и JSON-LD */
  en: { label: string; title: string; blurb: string };
  ru: { label: string; title: string; blurb: string };
}

export const MOODS: MoodDef[] = [
  {
    key: "swag",
    color: "#FFD400",
    glyph: "◆",
    en: {
      label: "swag",
      title: "Swag AI videos — style, flex & drip generated by machines",
      blurb:
        "Machine-made style: fashion flexes, impossible outfits, choreography no human body survives. Judge which clips are real swagger and which are pure synthesis.",
    },
    ru: {
      label: "свэг",
      title: "Swag AI-видео — стиль, флекс и дрип, сгенерированные машинами",
      blurb:
        "Машинный стиль: немыслимые аутфиты, хореография, которую человеческое тело не переживёт. Суди сам, где настоящий свэг, а где чистый синтетик.",
    },
  },
  {
    key: "creepy",
    color: "#FF2BA6",
    glyph: "✕",
    en: {
      label: "creepy",
      title: "Creepy AI videos — uncanny valley footage that shouldn't exist",
      blurb:
        "The uncanny valley, live: faces that almost breathe, rooms that almost make sense. The seam between real and synthetic is thinnest here — and the pools know it.",
    },
    ru: {
      label: "жуть",
      title: "Creepy AI-видео — зловещая долина в прямом эфире",
      blurb:
        "Зловещая долина в прямом эфире: лица, которые почти дышат, комнаты, которые почти сходятся. Шов между реальностью и синтетикой здесь тоньше всего.",
    },
  },
  {
    key: "future",
    color: "#00E5FF",
    glyph: "◑",
    en: {
      label: "future",
      title: "Future AI videos — machine dreams of tomorrow",
      blurb:
        "Tomorrow, rendered early: cities, interfaces and machines that don't exist yet. Watch what the models think 2035 looks like — then bet on whether any of it is footage.",
    },
    ru: {
      label: "будущее",
      title: "Future AI-видео — машинные сны о завтрашнем дне",
      blurb:
        "Завтра, отрендеренное раньше времени: города, интерфейсы и машины, которых ещё нет. Смотри, как модели представляют 2035-й — и решай, есть ли тут хоть кадр реальности.",
    },
  },
  {
    key: "ufo",
    color: "#7CFF4D",
    glyph: "✦",
    en: {
      label: "ufo",
      title: "UFO & anomaly AI videos — skies full of synthetic sightings",
      blurb:
        "Sightings, anomalies and skies that lie. The classic tape-versus-CGI debate reborn with generative video — the hardest calls on the whole hub.",
    },
    ru: {
      label: "нло",
      title: "UFO и аномалии — небеса, полные синтетических наблюдений",
      blurb:
        "Наблюдения, аномалии и небеса, которые врут. Классический спор «плёнка против CGI», перерождённый в эпоху генеративного видео — самые сложные решения на всём хабе.",
    },
  },
];

export const MOOD_KEYS = MOODS.map((m) => m.key);

export function getMood(key: string): MoodDef | undefined {
  return MOODS.find((m) => m.key === key);
}
