// @generated by scripts/gen-prompts-snapshot.mjs (npm run build) — не редактировать вручную
// Встроенная копия data/prompts.csv. СЕРВЕР-ОНИ: импортировать только из
// серверных модулей — полный текст промптов не должен попасть на клиент.
export const PROMPTS_CSV_SNAPSHOT = "utm_code,prompt_full\n";
