#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
no reality. — GEO/SEO стратегия хаба (v3) — тело документа (ReportLab).
Обложка рендерится отдельно (html2poster.js) и подшивается pypdf.

Numbering plan (Step 3.5):
| Outline | Type    | Chapter | Title                                   |
|---------|---------|---------|-----------------------------------------|
| 1       | cover   | —       | обложка (HTML/Playwright)               |
| 2       | toc     | —       | Содержание                              |
| 3       | content | 1       | Резюме: новое позиционирование          |
| 4       | content | 2       | Позиционирование и аудитории            |
| 5       | content | 3       | Семантическое ядро и кластеры           |
| 6       | content | 4       | GEO: протокол видимости для AI-движков  |
| 7       | content | 5       | Технический SEO-инвентарь               |
| 8       | content | 6       | Контент-план и воронка                  |
| 9       | content | 7       | KPI и метрики успеха                    |
| 10      | content | 8       | Риски и ограничения                     |
"""
import hashlib
import os
import sys

from reportlab.lib import colors
from reportlab.lib.enums import TA_CENTER, TA_LEFT
from reportlab.lib.pagesizes import A4
from reportlab.lib.styles import ParagraphStyle
from reportlab.lib.units import inch
from reportlab.pdfbase import pdfmetrics
from reportlab.pdfbase.pdfmetrics import registerFontFamily
from reportlab.pdfbase.ttfonts import TTFont
from reportlab.platypus import (CondPageBreak, KeepTogether, PageBreak,
                                Paragraph, SimpleDocTemplate, Spacer, Table,
                                TableStyle)
from reportlab.platypus.tableofcontents import TableOfContents

PDF_SKILL_DIR = "/home/z/my-project/skills/pdf"
sys.path.insert(0, os.path.join(PDF_SKILL_DIR, "scripts"))
from pdf import install_font_fallback  # noqa: E402

OUT = "/home/z/my-project/scripts/geo_body.pdf"

# ━━ Cascade Palette (auto-generated by design_engine.py palette-cascade) ━━
PAGE_BG       = colors.HexColor('#f3f4f4')
SECTION_BG    = colors.HexColor('#eaebeb')
CARD_BG       = colors.HexColor('#e4e7e8')
TABLE_STRIPE  = colors.HexColor('#ebedef')
HEADER_FILL   = colors.HexColor('#304956')
COVER_BLOCK   = colors.HexColor('#597786')
BORDER        = colors.HexColor('#aac0ca')
ICON          = colors.HexColor('#4d7183')
ACCENT        = colors.HexColor('#328ebd')
ACCENT_2      = colors.HexColor('#b35f43')
TEXT_PRIMARY  = colors.HexColor('#1e2021')
TEXT_MUTED    = colors.HexColor('#81878a')

TABLE_HEADER_COLOR = HEADER_FILL
TABLE_ROW_EVEN     = colors.white
TABLE_ROW_ODD      = TABLE_STRIPE

# ── шрифты: документ русский → FreeSerif (полная кириллица) ──
FONT_DIR = "/usr/share/fonts"
pdfmetrics.registerFont(TTFont("FreeSerif", f"{FONT_DIR}/truetype/freefont/FreeSerif.ttf"))
pdfmetrics.registerFont(TTFont("FreeSerif-Bold", f"{FONT_DIR}/truetype/freefont/FreeSerifBold.ttf"))
pdfmetrics.registerFont(TTFont("FreeSerif-Italic", f"{FONT_DIR}/truetype/freefont/FreeSerifItalic.ttf"))
pdfmetrics.registerFont(TTFont("FreeSerif-BoldItalic", f"{FONT_DIR}/truetype/freefont/FreeSerifBoldItalic.ttf"))
pdfmetrics.registerFont(TTFont("NotoSerifSC", f"{FONT_DIR}/truetype/noto-serif-sc/NotoSerifSC-Regular.ttf"))
pdfmetrics.registerFont(TTFont("NotoSerifSC-Bold", f"{FONT_DIR}/truetype/noto-serif-sc/NotoSerifSC-Bold.ttf"))
registerFontFamily("FreeSerif", normal="FreeSerif", bold="FreeSerif-Bold",
                   italic="FreeSerif-Italic", boldItalic="FreeSerif-BoldItalic")
registerFontFamily("NotoSerifSC", normal="NotoSerifSC", bold="NotoSerifSC-Bold")
install_font_fallback()

MARGIN = 1.0 * inch
PAGE_W, PAGE_H = A4
AVAIL_W = PAGE_W - 2 * MARGIN
AVAIL_H = PAGE_H - 2 * MARGIN
H1_ORPHAN = AVAIL_H * 0.25

DOC_TITLE = "no reality. — GEO/SEO стратегия интерактивного хаба AI-контента и предсказаний"

# ── стили ──
body = ParagraphStyle("Body", fontName="FreeSerif", fontSize=10.5, leading=17,
                      alignment=TA_LEFT, textColor=TEXT_PRIMARY,
                      spaceBefore=0, spaceAfter=8)
h1 = ParagraphStyle("H1", fontName="FreeSerif", fontSize=20, leading=26,
                    textColor=HEADER_FILL, spaceBefore=18, spaceAfter=10)
h2 = ParagraphStyle("H2", fontName="FreeSerif", fontSize=14, leading=19,
                    textColor=TEXT_PRIMARY, spaceBefore=14, spaceAfter=6)
bullet = ParagraphStyle("Bullet", fontName="FreeSerif", fontSize=10.5, leading=17,
                        alignment=TA_LEFT, textColor=TEXT_PRIMARY,
                        leftIndent=14, bulletIndent=2, spaceAfter=5)
quote = ParagraphStyle("Quote", fontName="FreeSerif-Italic", fontSize=10.5, leading=17,
                       alignment=TA_LEFT, textColor=TEXT_MUTED,
                       leftIndent=24, spaceBefore=4, spaceAfter=10)
cap = ParagraphStyle("Caption", fontName="FreeSerif", fontSize=8.5, leading=12,
                     alignment=TA_CENTER, textColor=TEXT_MUTED,
                     spaceBefore=3, spaceAfter=6)
th_style = ParagraphStyle("TH", fontName="FreeSerif", fontSize=10, leading=13,
                          textColor=colors.white, alignment=TA_CENTER)
td_style = ParagraphStyle("TD", fontName="FreeSerif", fontSize=9.5, leading=13,
                          textColor=TEXT_PRIMARY, alignment=TA_LEFT)
stat_style = ParagraphStyle("StatBig", fontName="FreeSerif", fontSize=21, leading=25,
                            textColor=ACCENT, alignment=TA_CENTER)
label_style = ParagraphStyle("StatLabel", fontName="FreeSerif", fontSize=8.5, leading=11,
                             textColor=TEXT_MUTED, alignment=TA_CENTER)
toc_l0 = ParagraphStyle("TOC0", fontName="FreeSerif", fontSize=12, leading=20,
                        leftIndent=20, textColor=TEXT_PRIMARY)
toc_title = ParagraphStyle("TOCTitle", fontName="FreeSerif", fontSize=18, leading=24,
                           textColor=HEADER_FILL, spaceAfter=14)


class TocDocTemplate(SimpleDocTemplate):
    def afterFlowable(self, flowable):
        if hasattr(flowable, "bookmark_name"):
            level = getattr(flowable, "bookmark_level", 0)
            text = getattr(flowable, "bookmark_text", "")
            key = getattr(flowable, "bookmark_key", "")
            self.notify("TOCEntry", (level, text, self.page, key))


def add_heading(text, style, level=0):
    key = "h_%s" % hashlib.md5(text.encode()).hexdigest()[:8]
    p = Paragraph('<a name="%s"/><b>%s</b>' % (key, text), style)
    p.bookmark_name = key
    p.bookmark_level = level
    p.bookmark_text = text
    p.bookmark_key = key
    return p


def section(story, num, title):
    story.append(CondPageBreak(H1_ORPHAN))
    story.append(add_heading("%d. %s" % (num, title), h1, level=0))


def para(story, text):
    story.append(Paragraph(text, body))


def bullets(story, items):
    for it in items:
        story.append(Paragraph(it, bullet, bulletText="•"))
    story.append(Spacer(1, 6))


def make_table(header, rows, ratios, caption=None):
    data = [[Paragraph("<b>%s</b>" % c, th_style) for c in header]]
    for r in rows:
        data.append([Paragraph(c, td_style) for c in r])
    widths = [x * AVAIL_W for x in ratios]
    assert abs(sum(ratios) - 1.0) < 0.01, "ratios must sum to 1"
    t = Table(data, colWidths=widths, hAlign="CENTER", repeatRows=1)
    style = [
        ("BACKGROUND", (0, 0), (-1, 0), TABLE_HEADER_COLOR),
        ("TEXTCOLOR", (0, 0), (-1, 0), colors.white),
        ("GRID", (0, 0), (-1, -1), 0.5, BORDER),
        ("VALIGN", (0, 0), (-1, -1), "MIDDLE"),
        ("LEFTPADDING", (0, 0), (-1, -1), 6),
        ("RIGHTPADDING", (0, 0), (-1, -1), 6),
        ("TOPPADDING", (0, 0), (-1, -1), 5),
        ("BOTTOMPADDING", (0, 0), (-1, -1), 5),
    ]
    for i in range(1, len(data)):
        style.append(("BACKGROUND", (0, i), (-1, i),
                      TABLE_ROW_ODD if i % 2 else TABLE_ROW_EVEN))
    t.setStyle(TableStyle(style))
    out = [Spacer(1, 12), t]
    if caption:
        out += [Spacer(1, 4), Paragraph(caption, cap)]
    out.append(Spacer(1, 10))
    return out


def callout_row(items):
    """Ряд из 3-4 метрик (CalloutBox)."""
    cells, w = [], AVAIL_W / len(items) - 8
    for big, small in items:
        inner = Table(
            [[Paragraph("<b>%s</b>" % big, stat_style)],
             [Paragraph(small, label_style)]],
            colWidths=[w],
        )
        inner.setStyle(TableStyle([
            ("BACKGROUND", (0, 0), (-1, -1), CARD_BG),
            ("BOX", (0, 0), (-1, -1), 1, ACCENT),
            ("TOPPADDING", (0, 0), (-1, -1), 8),
            ("BOTTOMPADDING", (0, 0), (-1, -1), 8),
            ("VALIGN", (0, 0), (-1, -1), "MIDDLE"),
        ]))
        cells.append(inner)
    row = Table([cells], colWidths=[AVAIL_W / len(items)] * len(items), hAlign="CENTER")
    row.setStyle(TableStyle([
        ("VALIGN", (0, 0), (-1, -1), "TOP"),
        ("LEFTPADDING", (0, 0), (-1, -1), 4),
        ("RIGHTPADDING", (0, 0), (-1, -1), 4),
    ]))
    return [Spacer(1, 10), row, Spacer(1, 12)]


def header_footer(canvas, doc):
    canvas.saveState()
    canvas.setFont("FreeSerif", 7.5)
    canvas.setFillColor(TEXT_MUTED)
    canvas.drawString(MARGIN, PAGE_H - 0.55 * inch,
                      "no reality. · GEO/SEO стратегия хаба v3")
    canvas.setStrokeColor(ACCENT)
    canvas.setLineWidth(1.2)
    canvas.line(MARGIN, PAGE_H - 0.62 * inch, PAGE_W - MARGIN, PAGE_H - 0.62 * inch)
    canvas.setStrokeColor(BORDER)
    canvas.setLineWidth(0.5)
    canvas.line(MARGIN, 0.62 * inch, PAGE_W - MARGIN, 0.62 * inch)
    canvas.setFillColor(TEXT_MUTED)
    canvas.drawString(MARGIN, 0.45 * inch, "no-reality.fun")
    canvas.drawRightString(PAGE_W - MARGIN, 0.45 * inch, "стр. %d" % doc.page)
    canvas.restoreState()


doc = TocDocTemplate(
    OUT, pagesize=A4,
    leftMargin=MARGIN, rightMargin=MARGIN,
    topMargin=MARGIN, bottomMargin=MARGIN,
    title=DOC_TITLE, author="Z.ai", creator="Z.ai",
    subject="GEO/SEO стратегия позиционирования no reality. как интерактивного хаба AI-контента и предсказаний",
)

story = []

# ───────────────────────── Содержание ─────────────────────────
toc = TableOfContents()
toc.levelStyles = [toc_l0]
story.append(Paragraph("<b>Содержание</b>", toc_title))
story.append(toc)
story.append(PageBreak())

# ───────────────────────── 1. Резюме ─────────────────────────
section(story, 1, "Резюме: новое позиционирование")
para(story,
     "«no reality.» переходит от позиционирования «вертикальная лента синтетического "
     "синема со ставками» к позиционированию <b>интерактивного хаба AI-контента и "
     "предсказаний</b>. Хаб остаётся игрой: каждый клип — реальная съёмка или машинный "
     "сон, зритель выносит вердикт REAL или SYNTH и ставит $1–5, пари-мьютюэль пул "
     "закрывается меньше чем за минуту. Меняется не механика, а рамка: ставка — "
     "ядро более широкой площадки про синтетические медиа и медиаграмотность, "
     "а не узкий гемблинг-продукт. Такая рамка лучше индексируется, цитируется "
     "генеративными движками и не попадает под жёсткие ограничения рекламы "
     "ставок, которые применяют поисковые системы к «чистым» букмекерским сайтам.")
para(story,
     "Новая стратегия уже внедрена в продукт: лента переосмыслена в мозаику "
     "(грид-дискавери с фильтрами по настроениям и режимом «слепого суда»), "
     "глубокие ссылки ведут в театр отдельного клипа, интерфейс двуязычный "
     "(русский и английский с hreflang), а поверх продукта собран GEO-слой — "
     "страницы-кластеры, структурированные данные, llms.txt и открытые правила "
     "для AI-краулеров. Рост аудитории измеряется вердиктами, пулами и "
     "реферальными цепочками, а не показами счётчиков просмотров, которые "
     "из интерфейса сознательно убраны.")
story.extend(callout_row([
    ("$1–5", "ставка на вердикт REAL/SYNTH"),
    ("<1 мин", "резолв раунда куратором"),
    ("20%", "рейка — рефереру навсегда"),
    ("~30%", "клипов мозаики — реальная съёмка"),
]))
para(story,
     "Документ фиксирует три вещи: как хаб теперь объясняет себя людям и машинам "
     "(позиционирование и семантика), какие технические артефакты уже работают "
     "на видимость (GEO-инвентарь) и по каким метрикам предлагается судить об "
     "успехе. Документ — рабочий: формулировки кластеров и KPI пересматриваются "
     "раз в квартал по фактическим данным Search Console и логам цитирований.")

# ───────────────────────── 2. Позиционирование ─────────────────────────
section(story, 2, "Позиционирование и аудитории")
para(story,
     "Ключевая фраза позиционирования: <b>«интерактивный хаб AI-контента и "
     "предсказаний»</b>. Слоган сохраняет харизма прежнего продукта — «watch what "
     "shouldn’t exist. call it. win the pool». В этой конструкции «хаб» задаёт "
     "категорию (площадка, а не лента), «AI-контент» — предметную область с "
     "растущим поисковым спросом, а «предсказания» — интерактивный слой, который "
     "отличает хаб от пассивных галерей генераций. Игровая механика REAL/SYNTH "
     "становится доказательством экспертности: хаб не рассказывает про проблему "
     "синтетических медиа, а ежедневно превращает её в измеримый навык.")
para(story,
     "Выделены четыре аудитории. Первая — «судьи»: молодая англоязычная и "
     "русскоязычная аудитория, которая развлекается угадыванием и делится "
     "клипами; для неё язык интерфейса — мозаика, вердикты и репутация. Вторая — "
     "«исследователи синтетики»: люди, которые гуглят «how to spot AI video», "
     "«real or AI generated» и приходят на объясняющие страницы кластера. Третья — "
     "«креаторы»: авторы промптов и синтетических роликов, для которых хаб — "
     "витрина и маркет промптов. Четвёртая — генеративные движки и их пользователи: "
     "ответы Perplexity, ChatGPT search и AI Overviews должны цитировать хаб как "
     "первоисточник определения игры REAL/SYNTH.")
story.extend(make_table(
    ["Аудитория", "Задача (JTBR)", "Продуктовый вход", "SEO-вход"],
    [
        ["Судьи", "проверить глаз, развлечься, поделиться", "/feed (мозаика), /v/CODE",
         "брендовые запросы, соцсети"],
        ["Исследователи", "научиться отличать AI-видео", "/real-or-synth, /moods/*",
         "информационные кластеры"],
        ["Креаторы", "показать промпт, заработать", "/market, авторские доли рейка",
         "запросы про промпты и Veo/Sora"],
        ["AI-движки", "дать точный ответ со ссылкой", "llms.txt, FAQPage, глоссарий",
         "цитирования в ответах"],
    ],
    [0.16, 0.30, 0.27, 0.27],
    "Таблица 1. Матрица аудиторий хаба и точек входа",
))

# ───────────────────────── 3. Семантика ─────────────────────────
section(story, 3, "Семантическое ядро и кластеры")
para(story,
     "Ядро собрано вокруг четырёх кластеров. Брендовый кластер защищает имя и "
     "слоган. Кластер «как отличить» собирает информационный спрос о распознавании "
     "генеративного видео — он самый большой по объёму и обслуживается страницей "
     "/real-or-synth и глоссарием. Кластер настроений агрегирует длинный хвост "
     "запросов про конкретные жанры AI-видео и обслуживается четырьмя каналами "
     "мозаики. Транзакционный кластер («ставки на AI», «crypto predictions») "
     "намеренно сужен: продукт остаётся игрой с рейком, но посадочные страницы "
     "не строятся вокруг азартной лексики — она остаётся на уровне глубоких "
     "страниц продукта, а не витрин.")
story.extend(make_table(
    ["Кластер", "Интент", "Примеры запросов (EN/RU)", "Целевая страница"],
    [
        ["Бренд", "навигационный", "no reality; no reality fun; но релиалити",
         "/", "/real-or-synth"],
        ["Как отличить AI-видео", "информационный",
         "how to spot ai generated video; real or synth; как отличить AI видео",
         "/real-or-synth"],
        ["Настроения-жанры", "информационно-развлекательный",
         "creepy ai video; ai ufo footage; свэг ai ролики", "/moods/swag … /moods/ufo"],
        ["Игра и ставки", "транзакционный",
         "ai prediction game; real or synth game; прогноз ai контент", "/feed, /v/CODE"],
        ["Промпты", "транзакционный",
         "veo prompt for sale; ai video prompts; купить промпт ai видео", "/market"],
    ],
    [0.20, 0.18, 0.38, 0.24],
    "Таблица 2. Кластеры семантического ядра и посадочные страницы",
))
para(story,
     "Приоритет внутри ядра задаёт правило «сначала вопросы, потом ставки»: "
     "страницы, отвечающие на вопросы о распознавании синтетики, получают "
     "внутренние ссылки из каждой карточки канала и из театра, тогда как игровые "
     "страницы индексируются, но не продвигаются прямой рекламой запросов о "
     "ставках. Такая схема согласует коммерческие цели с ограничениями рекламных "
     "политик и снижает риск классификации хаба как азартного сайта.")

# ───────────────────────── 4. GEO ─────────────────────────
section(story, 4, "GEO: протокол видимости для AI-движков")
para(story,
     "Generative Engine Optimization — это управление тем, что генеративные "
     "движки знают и цитируют. Для хаба внедрён полный протокол. Первый слой — "
     "разрешения: robots.txt явно разрешает GPTBot, OAI-SearchBot, ClaudeBot, "
     "PerplexityBot, Google-Extended и ещё пятнадцать сборщиков, закрывая только "
     "API и админку. Второй слой — машиночитаемое самописание: /llms.txt даёт "
     "краткую выжимку фактов о продукте, /llms-full.txt — полный бриф с "
     "позиционированием, механикой, экономикой и каналами. Третий слой — "
     "структурированные данные: факты хаба продублированы JSON-LD так, чтобы "
     "движок мог процитировать их без дополнительного парсинга.")
story.extend(make_table(
    ["Артефакт", "Назначение", "Где живёт"],
    [
        ["robots.txt (список AI-краулеров)", "явное разрешение сборки контента",
         "src/app/robots.ts"],
        ["/llms.txt и /llms-full.txt", "самописание для генеративных движков",
         "public/llms*.txt"],
        ["JSON-LD: WebSite, Organization, FAQPage, ItemList, Article, BreadcrumbList, CollectionPage",
         "факты и структура для цитирования и Rich Results", "страницы /, /feed, /real-or-synth, /moods/*"],
        ["FAQ (EN+RU) в разметке и в DOM", "готовые ответы на вопросы движков",
         "src/lib/hubFaq.ts"],
        ["Глоссарий суда (REAL, SYNTH, seam, blind court, pari-mutuel, rake)",
         "определения терминов, которые движки цитируют", "/real-or-synth"],
    ],
    [0.34, 0.36, 0.30],
    "Таблица 3. GEO-инвентарь хаба",
))
para(story,
     "Четвёртый слой — фактурирующий контент. Страница /real-or-synth написана "
     "как каноническое объяснение игры: что такое REAL и SYNTH, как работает "
     "пари-мьютюэль, почему вердикт никогда не покидает сервер до резолва. "
     "Каждая формулировка повторяется и в человеческом DOM, и в FAQPage-разметке, "
     "и в llms-full.txt — три согласированных источника одного факта. Каналы "
     "настроений дают движкам живые списки клипов (ItemList), а анти-чит "
     "правило «truth не попадает в клиентский бандл» зафиксировано в тексте "
     "как гарантия честности — это тот тип деталей, который движки любят "
     "цитировать в ответах о механике.")

# ───────────────────────── 5. Техинвентарь ─────────────────────────
section(story, 5, "Технический SEO-инвентарь (внедрено)")
para(story,
     "Техническая база собрана и проверена. Единая точка правды SITE управляет "
     "метаданными всех маршрутов; sitemap.xml охватывает хаб, мозаику, кластер "
     "и легаси-разделы с приоритетами и частотами обновления; hreflang связывает "
     "английскую и русскую версии (en, ru, x-default), включая вариант «?lang=ru» "
     "для шареных ссылок. Каждая страница отдаёт canonical, Open Graph и Twitter "
     "карточки; для глубоких ссылок /v/CODE генерируется мета-карточка «REAL or "
     "SYNTH?» с заголовком клипа, а новая OG-графика в стиле VHS-zine сделана "
     "для хаба и каналов. Страницы кластера статичны и отдаются быстро; "
     "мозаика и театр остаются динамическими, но их HTML валиден для краулеров "
     "без выполнения JavaScript.")
bullets(story, [
    "sitemap.xml: 12 маршрутов с hreflang-альтернейтами и приоритетами (хаб 1.0, мозаика 0.9, кластер 0.8–0.9);",
    "hreflang en/ru/x-default на всех страницах кластера и хаба; язык UI переключается и шарится через ?lang=ru;",
    "OG-графика VHS-zine (1200×630) для хаба; для /v/CODE — метаданные с вопросом REAL or SYNTH?;",
    "JSON-LD граф хаба: WebSite + Organization + ItemList настроений + FAQPage из 7 вопросов;",
    "llms.txt (краткий) и llms-full.txt (полный бриф) с фактами экономики и механики;",
    "JSON-LD CollectionPage + ItemList на /feed и каналах — живой каталог клипов для движков.",
])
para(story,
     "Из осознанных исключений: видео Threads-CDN не хотлинкается в sitemap как "
     "VideoObject, потому что подписанные ссылки живут недолго; вместо этого "
     "движкам отдаются стабильные URL страниц суда. Диплинки /v/CODE бесконечны "
     "и в sitemap не попадают — их индексация идёт через внутренние ссылки "
     "мозаики и шареные ссылки с реферальными кодами.")

# ───────────────────────── 6. Контент-план ─────────────────────────
section(story, 6, "Контент-план и воронка")
para(story,
     "Воронка хаба — «увидел шэр → открыл клип → вынес вердикт → привёл глаз». "
     "Контент-план обслуживает каждый шаг. Шэры генерирует сама механика: "
     "каждый клип несёт глубокую ссылку и реферальный код, а режим слепого суда "
     "даёт повод поделиться «проверь себя». Объясняющий контент выпускается "
     "редакционно и живёт на кластерных страницах; его задача — перевести "
     "поисковый интерес в первого судью. Каналы настроений обновляются ежедневно "
     "кураторской разметкой, поэтому движки видят живой каталог, а не витрину.")
story.extend(make_table(
    ["Тип контента", "Частота", "Цель", "Метрика успеха"],
    [
        ["Новые клипы и раунды (куратор)", "ежедневно, 8–12 шт.",
         "возвраты судей, материал для шэров", "вердикты на клип, доля беттабельных"],
        ["Канальные страницы /moods/*", "обновление ежедневно",
         "длинный хвост жанровых запросов", "позиции и клики Search Console"],
        ["Разборы «как отличить» (статьи на /real-or-synth)", "2 в месяц",
         "информационный трафик, E-E-A-T", "цитирования в AI-ответах, позиции"],
        ["FAQ-пополнение (EN+RU)", "ежемесячно", "новые вопросы движков",
         "показы FAQ Rich Results"],
        ["Telegram-дропы лучшего", "ежедневно", "реактивация и виральный цикл",
         "переходы с ?ref=, конверсия в вердикт"],
    ],
    [0.30, 0.16, 0.28, 0.26],
    "Таблица 4. Контент-план воронки хаба",
))

# ───────────────────────── 7. KPI ─────────────────────────
section(story, 7, "KPI и метрики успеха")
para(story,
     "Хаб сознательно не публикует охваты: счётчики просмотров убраны из "
     "интерфейса, а рост измеряется активностью и цепочками. Это же правило "
     "перенесено на аналитику: вместо показов и просмотров ядром метрик "
     "становятся вердикты (bet_placed), резолвы (bet_won/bet_lost), шэры "
     "(share_click) и конверсия реферальной цепочки (ref_click → ref_converted). "
     "SEO-метрики дополняют продуктовые: позиции кластера, клики из Search "
     "Console и цитирования в генеративных ответах, которые отслеживаются "
     "ежемесячным срезом по ключевым вопросам.")
story.extend(make_table(
    ["Группа", "Метрика", "Базовый ориентир 3 мес.", "Цель 6 мес."],
    [
        ["Продукт", "вердиктов в сутки", "150–300", "1000+"],
        ["Продукт", "доля судей, вернувшихся на 2-й день", "15–20%", "30%"],
        ["Виральность", "share_click → переход по /v/CODE", "25–35%", "45%"],
        ["Рефералка", "новых глаз через ?ref= в неделю", "30–60", "200+"],
        ["SEO", "кластер «как отличить» в топ-20", "2–3 запроса", "12+ запросов"],
        ["GEO", "цитирования в AI-ответах (срез 10 вопросов)", "1–2", "5+ движков"],
    ],
    [0.16, 0.34, 0.25, 0.25],
    "Таблица 5. KPI хаба по группам (ориентиры пересматриваются quarterly)",
))
para(story,
     "Каждой метрике назначен источник: продуктовые события пишутся в TrackEvent "
     "(bet_*, share_click, ref_*), SEO — в Search Console, GEO — в ручной срез "
     "ответов Perplexity/ChatGPT/Google AI по фиксированному списку вопросов. "
     "Пороговая санкция для кураторского контента: если доля беттабельных клипов "
     "в мозаике падает ниже 50%, приостанавливается выпуск разборов в пользу "
     "разметки, потому что игра без ставок не производит шэров.")

# ───────────────────────── 8. Риски ─────────────────────────
section(story, 8, "Риски и ограничения")
para(story,
     "Главный репутационный риск — классификация хаба как азартного продукта. "
     "Смягчения уже встроены: ставки $1–5, пари-мьютюэль без офферов против "
     "дома, отсутствие рекламного контура вокруг азартной лексики и рамка "
     "«хаб AI-контента», в которой ставка — игровой слой, а не суть категории. "
     "Технический риск — зависимость от CDN Threads: подписанные ссылки живут "
     "недолго, поэтому мозаика деградирует в «signal lost»-карточки, а страницы "
     "кластера не зависят от внешних ссылок вовсе. Контентный риск — ползучая "
     "утечка вердиктов через сторонние сайты: она купируется серверным резолвом "
     "и тем, что truth никогда не отдаётся клиенту.")
bullets(story, [
    "Правовая рамка: 18+ в терминах, запрет юрисдикций, где пари-мьютюэль требует лицензии — пересматривается перед платным трафиком;",
    "Платёжный контур: выплаты и кэшаут только через подписанные webhook-события 2328.io, claim только после успешного payout-инвойса;",
    "Модерация: кураторская разметка truth/mood перед публикацией, целевые ~30% реальных клипов в мозаике;",
    "Демонетизация охватов: никаких публичных счётчиков просмотров — интерфейс показывает только вердикты, пулы и репутацию.",
])
para(story,
     "Следующие шаги плана: ежемесячный срез GEO-цитирований с фиксацией "
     "формулировок; эксперимент с отдельной страницей-глоссарием под запросы "
     "«what is pari-mutuel» и «blind judgment test»; локализация разборов "
     "«как отличить» на русский в полном объёме; подключение альтернативного "
     "CDN для клипов, чтобы снизить зависимость от Threads. Все четыре шага "
     "не требуют изменений в игровой механике и укладываются в текущий "
     "релизный цикл.")

doc.multiBuild(story, onFirstPage=header_footer, onLaterPages=header_footer)
print("body OK:", OUT)
